//-------1---------2---------3---------4---------5---------6---------7---------8---------9
// title break macro
:v: pass:q[<br>]
// forcing indentation
:__: {nbsp}{nbsp}

= Dev Environment for T4C {v} Version 6.1.0
// Author line
Freddy K. Simo <fksimo@obeo.fr>, N. Péransin
:revnumber: v1.0
:revdate: 2023-06-09
:revremark: Draft
:doctype: book

:sectnums:
:sectnumlevels: 1
// PDF use a specific chapter prefix
:chapter-label: 

:toc:

<<<

== Required resources

T4C (TeamForCapella-6.1.0-<os.arch>.zip) ::
  http://update.obeo.fr/release/team-for-capella/6.1/6.1.0/packages/

TeamForCapella_InstallationGuide_6.1.0.pdf ::
  https://update.obeo.fr/release/team-for-capella/6.1/6.1.0/packages/TeamForCapella_InstallationGuide_6.1.0.pdf

Extended Capella (Auriga 6.1) including T4C client-part ::
  http://update.obeo.fr/release/auriga/6.1/6.1.0/packages/

Public Capella 6.1.0 ::
  https://github.com/eclipse/capella/releases/tag/v6.1.0


<<<

== Server side

=== Installation

Details at Section 3.4.1 Team For Capella Server Installation Procedure of 
_TeamForCapella_InstallationGuide_6.1.0_.

 * Unzip the downloaded T4C archive into a T4C folder.
 * Unzip the Capella client into a T4C folder. 
 * Verify expected folder layout:
 ** capella
 ** lic-server
 ** license.html
 ** samples
 ** server
 ** tools
 ** updateSite
 * Run `installTeamForCapellaInCapella.bat`

=== Running

[options="header",cols="1,3"]
|===
|Action   | Command line
|Start    | Run the `serverc.exe` located in the folder `server` itself located in T4C 
            folder.
|Stop    a| * Press Enter to see the osgi> prompt;
            * Input `exit` and press Enter; 
            * Input `y` and press Enter.
|===

<<<

== Client side

The following is also detailled in Section 4.2.1.1 of 
_TeamForCapella_InstallationGuide_6.1.0_.

=== Installation

==== Capella Extended case

 * Unzip the downloaded Capella extented archive into the folder where T4C has been 
   unzipped (there should be only two new folders: `capella` and `samples`)


==== Classic Capella case

 . Unzip the downloaded classic Capella  archive into a folder named  `capella` : the 
   Capella executable must directly be inside this folder
 . Move this folder named `capella` into the folder where T4C has been unzipped
 .. Ensure there are folders `updateSite` and `tools` besides the `capella` folder and 
    others in the T4C folder
 . Open a command line in the folder `tools` and run the command 
   `.\installTeamForCapellaInCapella.bat`
 .. In case you are not on a Windows system, follow the steps in Section 4.2.2 of
    _TeamForCapella_InstallationGuide_6.1.0_ from step 3.


==== Activating Development license

After performing either of the above cases,

 * In the folder `capella`, edit the file `capella.ini`
 ** Replace the value of the key `-DOBEO_LICENSE_SERVER_CONFIGURATION` with the one 
    available here: https://obeo-licserver.obeo.fr/
 ** To use this license for connections to T4C from Capella, you must be in the Obeo 
    intranet network, otherwise, i.e., if you are not (or cannot be) on the Obeo intranet 
    network, you must request a personal licence.


=== Running

As usual :)

<<<

== Testing with server and client running

The credentials (login and password) used for testing purposes are located at: 
`T4C folder/server/configuration/users.properties`.
 
=== Connection to T4C from Capella
The following is also (partially) available in  Section 4.2.2, 3 of 
_TeamForCapella_InstallationGuide_6.1.0_.

In Capella, 

 * Click on Window > Preferences > Sirius > Team collaboration
 * On the entry with Alias equals `Default`, edit and replace `10.0.0.5`, if present, with 
   `localhost`
 * Apply and close


=== Sharing a project on server

The content of this section is also (partially) available in Section 4.2.3 of
_TeamForCapella_InstallationGuide_6.1.0_.

IMPORTANT: To activate an extension on a Capella Connected project or a shared Capella 
project via T4C, the extension must first have been activated in a local project, 
which will then have been exported to T4C, 
and only then does the Capella Connected project reference this exported project.

In Capella,

 * Install your extension(s) or add-on(s)
 * Create or import a Capella project
 * Activate your extension(s) in the Viewpoint manager view
 * In order to test CDO compliance, create model elements specific to your extension(s) 
   and save
 * Right click on the project > Export > Team for Capella > Capella Project to Remote 
   Repository > Next
 * Click on Test Connection (use `user1` as the login and password, if required)
 ** The result must be: Repository connection can be established
 * Click on Finish
 ** If no error is displayed, the project is exported on T4C
 ** Check error log in case no successful prompt is displayed

=== Working on a shared project

The content of this section is also (partially) available in Section 4.2.3 of
_TeamForCapella_InstallationGuide_6.1.0_.

In Capella,

 *  In the Capella _Project Explorer_, right click *New > Capella Connected Project*
 *  Click on 'Test Connection' (if required, use `user1` as the login and password)
 ** The result must be: "Repository connection can be established"
 *  Select the remote project from the list (it ends with .aird)
 *  Click on Finish
 ** If no error is displayed, an eclipse project is created that references the selected 
    shared project
 * Check your extension(s) is/are active